version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: http://backend:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/workspace:cached
      - m2_cache:/home/appuser/.m2
    command: ./mvnw spring-boot:run
    tty: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/somadev
      - SPRING_DATASOURCE_USERNAME=soma
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=somadev
      - POSTGRES_USER=soma
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  m2_cache:
  postgres_data: 