version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: soma_backend
    ports:
      - "8081:8080"
    env_file:
      - ./.env
    environment:
      - JAVA_OPTS=-Xmx400m -Xms200m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: soma_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_buffers=128MB -c max_connections=50 -c effective_cache_size=256MB

volumes:
  postgres_data: 