version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: soma_backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: soma_db
    restart: always
    environment:
      - POSTGRES_USER=soma
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=soma_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 