version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/workspace:cached
      - m2_cache:/home/appuser/.m2
    command: ./mvnw spring-boot:run
    tty: true

volumes:
  m2_cache: 