version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/somadevfat/soma-pages/backend:latest # Replace with your actual production image
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - CONTENT_ROOT_PATH=/app/content
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: ghcr.io/somadevfat/soma-pages/frontend:latest # Replace with your actual production image
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL_INTERNAL=http://backend:8080/api
      - NEXT_PUBLIC_API_BASE_URL=/api/proxy
    depends_on:
      - backend

volumes:
  postgres_data: 