version: '3.8'

services:
  backend:
    image: ghcr.io/somadevfat/somadev-pages/backend:latest
    container_name: soma_backend_prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/somadb
      - SPRING_DATASOURCE_USERNAME=soma
      - SPRING_DATASOURCE_PASSWORD=somapassword
      - JWT_SECRET=your-very-long-secret-key-for-production-at-least-32-characters
      - ADMIN_PASSWORD=admin123
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: soma_db_prod
    restart: always
    environment:
      - POSTGRES_DB=somadb
      - POSTGRES_USER=soma
      - POSTGRES_PASSWORD=somapassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_prod: 