name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  packages: write

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint
      run: npm run lint
    
    - name: Run build
      run: npm run build

  backend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Run backend tests
      run: cd backend && ./mvnw test
    
    - name: Upload surefire reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: backend/target/surefire-reports/
        retention-days: 30

  e2e-test:
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Run E2E tests
      env:
        E2E_TEST_USER_EMAIL: ${{ secrets.E2E_TEST_USER_EMAIL }}
        E2E_TEST_USER_PASSWORD: ${{ secrets.E2E_TEST_USER_PASSWORD }}
      run: npm run test:e2e:docker
    
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Cleanup Docker
      if: always()
      run: npm run test:e2e:docker:clean

  publish-ghcr:
    name: Publish to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test]
    # mainブランチへのpushイベントでのみ実行
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for frontend image
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/frontend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.frontend
          push: true
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=/api/proxy
            API_BASE_URL_INTERNAL=http://backend:8080/api

      - name: Extract metadata for backend image
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}

  deploy:
    name: Deploy to GCP Compute Engine
    runs-on: ubuntu-latest
    needs: [publish-ghcr] # publish-ghcrジョブの完了を待つ

    permissions:
      contents: read
      id-token: write # OIDC認証に必要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Enable necessary APIs
        run: gcloud services enable iamcredentials.googleapis.com --project=${{ vars.GCP_PROJECT_ID }}

      - name: Copy compose file to GCE
        run: |
          gcloud compute scp docker-compose.prod.yml somahiranodev@${{ vars.GCP_VM_NAME }}:/opt/somadev-pages/docker-compose.prod.yml --zone=${{ vars.GCP_ZONE }} --project=${{ vars.GCP_PROJECT_ID }}

      - name: Deploy to GCE
        env:
          GCE_INSTANCE: ${{ vars.GCP_VM_NAME }}
          GCE_PROJECT: ${{ vars.GCP_PROJECT_ID }}
          GCE_ZONE: ${{ vars.GCP_ZONE }}
          GH_USER: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GHCR_PAT }}
        run: |
          gcloud compute ssh somahiranodev@"$GCE_INSTANCE" --zone "$GCE_ZONE" --project "$GCE_PROJECT" --command="
            set -e
            
            echo 'Logging into GitHub Container Registry...'
            echo '$GH_TOKEN' | docker login ghcr.io -u $GH_USER --password-stdin

            echo 'Navigating to project directory...'
            cd /opt/somadev-pages

            echo 'Stopping and removing existing containers and volumes...'
            docker-compose -f docker-compose.prod.yml down --remove-orphans --volumes

            echo 'Pruning dangling containers and volumes...'
            docker container prune -f
            docker volume prune -f

            echo 'Pulling latest images from GHCR...'
            docker-compose -f docker-compose.prod.yml pull

            echo 'Starting application with new images (force recreate)...'
            docker-compose -f docker-compose.prod.yml up -d --force-recreate --remove-orphans

            echo 'Cleaning up unused Docker images...'
            docker image prune -af

            echo 'Deployment to GCE completed successfully!'
          " 