name: Deploy to GCP VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: read # デプロイは読み取りだけで良い

jobs:
  deploy:
    name: Deploy to GCP Compute Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Copy compose file to GCE
        run: |
          gcloud compute scp docker-compose.prod.yml somahiranodev@${{ vars.GCE_INSTANCE_NAME }}:/opt/somadev-pages/docker-compose.prod.yml --zone=${{ vars.GCP_ZONE }} --project=${{ vars.GCP_PROJECT_ID }}

      - name: Deploy to GCE
        env:
          GCE_INSTANCE: ${{ vars.GCE_INSTANCE_NAME }}
          GCE_PROJECT: ${{ vars.GCP_PROJECT_ID }}
          GCE_ZONE: ${{ vars.GCP_ZONE }}
          GH_USER: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GHCR_PAT }}
        run: |
          gcloud compute ssh somahiranodev@"$GCE_INSTANCE" --zone "$GCE_ZONE" --project "$GCE_PROJECT" --command="
            set -e
            
            echo 'Logging into GitHub Container Registry...'
            echo '$GH_TOKEN' | docker login ghcr.io -u $GH_USER --password-stdin

            echo 'Navigating to project directory...'
            cd /opt/somadev-pages

            echo 'Pulling latest images from GHCR...'
            docker-compose -f docker-compose.prod.yml pull

            echo 'Starting application with new images...'
            docker-compose -f docker-compose.prod.yml up -d --remove-orphans

            echo 'Cleaning up unused Docker images...'
            docker image prune -af

            echo 'Deployment to GCE completed successfully!'
          " 